# Generated by Django 6.0.7 on 2026-07-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, default='', help_text='프론트에서 알림 클릭 시 이동할 경로 (예: /policies/{item_id})', max_length=300),
        ),
    ]