# Generated by Django 6.0.6 on 2026-07-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_comment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='comment',
            new_name='community_c_post_id_bea033_idx',
            old_name='community_c_post_id_9f1a3b_idx',
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
