# Generated by Django 6.0.7 on 2026-07-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_rename_community_c_post_id_9f1a3b_idx_community_c_post_id_bea033_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitypost',
            name='category',
            field=models.CharField(choices=[('general', '일반'), ('housing', '주거'), ('finance', '금융'), ('employment', '취업'), ('education', '교육'), ('startup', '창업'), ('etc', '기타')], db_index=True, default='general', max_length=20),
        ),
    ]