# Generated by Django 5.2.15 on 2026-07-08 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_communitypostlike'),
        ('community', '0006_like'),
    ]

    operations = [
    ]
