# Generated by Django 6.0.7 on 2026-07-08 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_merge_0005_communitypostlike_0006_like'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='communitypostlike',
            name='community_c_post_id_be8361_idx',
        ),
        migrations.RemoveConstraint(
            model_name='communitypostlike',
            name='unique_community_post_like',
        ),
        migrations.DeleteModel(
            name='CommunityPostLike',
        ),
    ]