<<<<<<< HEAD
# Generated manually for email verification.

import django.core.validators
=======
# Generated by Django 5.2.15 on 2026-07-07 09:22

>>>>>>> 50c67f79ae02d80099f0dcb29ad86131bb44f18a
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ("users", "0001_initial"),
=======
        ('users', '0001_initial'),
>>>>>>> 50c67f79ae02d80099f0dcb29ad86131bb44f18a
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name="EmailVerificationCode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("code", models.CharField(max_length=6, validators=[django.core.validators.MinLengthValidator(6)])),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("signup", "회원가입"),
                            ("password_reset", "비밀번호 재설정"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("is_used", models.BooleanField(default=False)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["email", "purpose", "-created_at"], name="users_email_verify_lookup"),
                ],
=======
            name='EmailVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('code', models.CharField(max_length=6)),
                ('purpose', models.CharField(choices=[('signup', '회원가입'), ('password_reset', '비밀번호 재설정')], max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['email', 'purpose', 'code'], name='users_email_email_711d3d_idx')],
>>>>>>> 50c67f79ae02d80099f0dcb29ad86131bb44f18a
            },
        ),
    ]
