# Generated by Django 6.0.6 on 2026-07-03 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('item_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('source_category', models.CharField(choices=[('policy', '정책'), ('startup_notice', '창업공고'), ('training', '훈련과정')], db_index=True, max_length=30)),
                ('title', models.CharField(max_length=300)),
                ('domain', models.CharField(blank=True, max_length=200)),
                ('policy_summary', models.TextField(blank=True)),
                ('participation_target', models.CharField(blank=True, max_length=300)),
                ('region_codes', models.JSONField(blank=True, default=list)),
                ('income_condition', models.TextField(blank=True, default='')),
                ('application_period_text', models.CharField(blank=True, max_length=200)),
                ('application_start_date', models.DateField(blank=True, null=True)),
                ('application_end_date', models.DateField(blank=True, null=True)),
                ('application_url', models.URLField(blank=True, max_length=500)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('source_url_2', models.URLField(blank=True, max_length=500)),
                ('info_score', models.IntegerField(default=0)),
                ('needs_detail_check', models.BooleanField(default=False)),
                ('deadline_status', models.CharField(choices=[('upcoming', '예정'), ('ongoing', '진행중'), ('closing_soon', '마감임박'), ('closed', '마감'), ('unknown', '미확인')], db_index=True, default='unknown', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '정책',
                'verbose_name_plural': '정책',
                'db_table': 'policies',
                'indexes': [models.Index(fields=['source_category'], name='policies_source__f5714f_idx'), models.Index(fields=['deadline_status'], name='policies_deadlin_8872fb_idx')],
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '검색 기록',
                'verbose_name_plural': '검색 기록',
                'db_table': 'search_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Scrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrapped_by', to='policies.policy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '스크랩',
                'verbose_name_plural': '스크랩',
                'db_table': 'scraps',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'policy')},
            },
        ),
        migrations.CreateModel(
            name='ViewedPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_by', to='policies.policy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '최근 본 공고',
                'verbose_name_plural': '최근 본 공고',
                'db_table': 'viewed_policies',
                'ordering': ['-viewed_at'],
                'unique_together': {('user', 'policy')},
            },
        ),
    ]
