# Generated by Django 6.0.6 on 2026-07-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='age_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='age_min',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
