# Generated by Django 6.0.6 on 2026-07-07 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0003_add_extended_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularSearchKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(db_index=True, max_length=50, unique=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('last_searched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '인기 검색어',
                'verbose_name_plural': '인기 검색어',
                'db_table': 'popular_search_keywords',
                'ordering': ['-count', 'keyword'],
                'indexes': [models.Index(fields=['-count', 'keyword'], name='popular_sea_count_e02b83_idx')],
            },
        ),
    ]
